nome = input('Digite seu nome completo: ')
print(f'O nome em letras maiúsculas é: {nome.upper()}.')
print(f'O nome em letras minúsculas é: {nome.lower()}.')
print(f'O nome possui {len(nome.replace(" ", ""))} letras no total.')
print(f'O primeiro nome possui {len(nome.split(" ")[0])} letras.')