x = input('Digite qualquer coisa: ')
print('O tipo primitivo deste valor é', type(x))
print('É alfabético?', x.isalpha())
print('É numérico?', x.isnumeric())
print('É alfanumérico?', x.isalnum())
print('É imprimível?', x.isprintable())
print('É um espaço?', x.isspace())
print('Está em maiúsculas?', x.isupper())
print('Está em minúsculas?', x.islower())
print('Está capitalizada?', x.istitle())    